plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'io.freefair.lombok' version '8.6'
    id 'org.flywaydb.flyway' version '9.22.3'
}

group = 'com.samverk'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.security:spring-security-config'
    implementation 'org.springframework.security:spring-security-web'
    implementation 'org.flywaydb:flyway-core'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'org.postgresql:postgresql:42.7.3'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    implementation 'jakarta.annotation:jakarta.annotation-api:3.0.0-M1'
    implementation("org.springframework.boot:spring-boot-starter-logging") {
        exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
    }
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
}

tasks.named('test') {
    useJUnitPlatform()
}

springBoot {
    mainClass = 'com.samverk.SamverkWebApplication'
}

sourceSets {
    main {
        java {
            srcDirs = ['backend/src/main/java']
        }
        resources {
            srcDirs = ['backend/src/main/resources']
        }
    }
    test {
        java {
            srcDirs = ['backend/src/test/java']
        }
        resources {
            srcDirs = ['backend/src/test/resources']
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

flyway {
    url = 'jdbc:postgresql://localhost:5433/samverk'
    user = 'postgres'
    password = 'postgres'
    schemas = ['samverk']
    locations = ['classpath:db/migration']
}
