plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.4'
	id 'io.spring.dependency-management' version '1.1.4'
	
	// Add lombok plugin
	id "io.freefair.lombok" version "8.6"
}

java {
	sourceCompatibility = '21'
}

springBoot {
    mainClass = 'samverk.SamverkWebApplication'
}

sourceSets {
    main {
        java {
            srcDirs 'backend/src/main/java/com/samverk'
        }
    }
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.flywaydb:flyway-core'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	
	// Add jakarta annotation
	implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'

	// Exclude the default logging dependencies
    implementation("org.springframework.boot:spring-boot-starter-logging") {
        exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
    }
    
    // Add the logging framework dependency
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
}

tasks.named('test') {
	useJUnitPlatform()
}
