spring.application.name=samverkWebApplication

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway configuration
spring.flyway.enabled=true

# Logging level for Flyway
logging.level.org.flywaydb=DEBUG