# DataSource configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/samverk?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=postgres

# Loging config for log4j
logging.config=classpath:log4j2-local.xml