INSERT INTO country (country_code, country_name, country_phone_prefix) VALUES
('AD', 'Andorra', '+376'),
('AE', 'United Arab Emirates', '+971'),
('AF', 'Afghanistan', '+93'),
('AG', 'Antigua and Barbuda', '+1-268'),
('AI', 'Anguilla', '+1-264'),
('AL', 'Albania', '+355'),
('AM', 'Armenia', '+374'),
('AO', 'Angola', '+244'),
('AQ', 'Antarctica', NULL),
('AR', 'Argentina', '+54'),
('AS', 'American Samoa', '+1-684'),
('AT', 'Austria', '+43'),
('AU', 'Australia', '+61'),
('AW', 'Aruba', '+297'),
('AX', 'Åland Islands', '+358-18'),
('AZ', 'Azerbaijan', '+994'),
('BA', 'Bosnia and Herzegovina', '+387'),
('BB', 'Barbados', '+1-246'),
('BD', 'Bangladesh', '+880'),
('BE', 'Belgium', '+32'),
('BF', 'Burkina Faso', '+226'),
('BG', 'Bulgaria', '+359'),
('BH', 'Bahrain', '+973'),
('BI', 'Burundi', '+257'),
('BJ', 'Benin', '+229'),
('BL', 'Saint Barthélemy', '+590'),
('BM', 'Bermuda', '+1-441'),
('BN', 'Brunei Darussalam', '+673'),
('BO', 'Bolivia, Plurinational State of', '+591'),
('BQ', 'Bonaire, Sint Eustatius and Saba', '+599'),
('BR', 'Brazil', '+55'),
('BS', 'Bahamas', '+1-242'),
('BT', 'Bhutan', '+975'),
('BV', 'Bouvet Island', NULL),
('BW', 'Botswana', '+267'),
('BY', 'Belarus', '+375'),
('BZ', 'Belize', '+501'),
('CA', 'Canada', '+1'),
('CC', 'Cocos (Keeling) Islands', '+61'),
('CD', 'Congo, Democratic Republic of the', '+243'),
('CF', 'Central African Republic', '+236'),
('CG', 'Congo', '+242'),
('CH', 'Switzerland', '+41'),
('CI', E'C\u00f4te d''Ivoire', '+225'),
('CK', 'Cook Islands', '+682'),
('CL', 'Chile', '+56'),
('CM', 'Cameroon', '+237'),
('CN', 'China', '+86'),
('CO', 'Colombia', '+57'),
('CR', 'Costa Rica', '+506'),
('CU', 'Cuba', '+53'),
('CV', 'Cabo Verde', '+238'),
('CW', 'Curaçao', '+599'),
('CX', 'Christmas Island', '+61'),
('CY', 'Cyprus', '+357'),
('CZ', 'Czechia', '+420'),
('DE', 'Germany', '+49'),
('DJ', 'Djibouti', '+253'),
('DK', 'Denmark', '+45'),
('DM', 'Dominica', '+1-767'),
('DO', 'Dominican Republic', '+1-809'),
('DZ', 'Algeria', '+213'),
('EC', 'Ecuador', '+593'),
('EE', 'Estonia', '+372'),
('EG', 'Egypt', '+20'),
('EH', 'Western Sahara', '+212'),
('ER', 'Eritrea', '+291'),
('ES', 'Spain', '+34'),
('ET', 'Ethiopia', '+251'),
('FI', 'Finland', '+358'),
('FJ', 'Fiji', '+679'),
('FK', 'Falkland Islands (Malvinas)', '+500'),
('FM', 'Micronesia, Federated States of', '+691'),
('FO', 'Faroe Islands', '+298'),
('FR', 'France', '+33'),
('GA', 'Gabon', '+241'),
('GB', 'United Kingdom of Great Britain and Northern Ireland', '+44'),
('GD', 'Grenada', '+1-473'),
('GE', 'Georgia', '+995'),
('GF', 'French Guiana', '+594'),
('GG', 'Guernsey', '+44'),
('GH', 'Ghana', '+233'),
('GI', 'Gibraltar', '+350'),
('GL', 'Greenland', '+299'),
('GM', 'Gambia', '+220'),
('GN', 'Guinea', '+224'),
('GP', 'Guadeloupe', '+590'),
('GQ', 'Equatorial Guinea', '+240'),
('GR', 'Greece', '+30'),
('GS', 'South Georgia and the South Sandwich Islands', NULL),
('GT', 'Guatemala', '+502'),
('GU', 'Guam', '+1-671'),
('GW', 'Guinea-Bissau', '+245'),
('GY', 'Guyana', '+592'),
('HK', 'Hong Kong', '+852'),
('HM', 'Heard Island and McDonald Islands', NULL),
('HN', 'Honduras', '+504'),
('HR', 'Croatia', '+385'),
('HT', 'Haiti', '+509'),
('HU', 'Hungary', '+36'),
('ID', 'Indonesia', '+62'),
('IE', 'Ireland', '+353'),
('IL', 'Israel', '+972'),
('IM', 'Isle of Man', '+44'),
('IN', 'India', '+91'),
('IO', 'British Indian Ocean Territory', '+246'),
('IQ', 'Iraq', '+964'),
('IR', 'Iran, Islamic Republic of', '+98'),
('IS', 'Iceland', '+354'),
('IT', 'Italy', '+39'),
('JE', 'Jersey', '+44'),
('JM', 'Jamaica', '+1-876'),
('JO', 'Jordan', '+962'),
('JP', 'Japan', '+81'),
('KE', 'Kenya', '+254'),
('KG', 'Kyrgyzstan', '+996'),
('KH', 'Cambodia', '+855'),
('KI', 'Kiribati', '+686'),
('KM', 'Comoros', '+269'),
('KN', 'Saint Kitts and Nevis', '+1-869'),
('KP', E'Korea, Democratic People''s Republic of', '+850'),
('KR', 'Korea, Republic of', '+82'),
('KW', 'Kuwait', '+965'),
('KY', 'Cayman Islands', '+1-345'),
('KZ', 'Kazakhstan', '+7'),
('LA', E'Lao People''s Democratic Republic', '+856'),
('LB', 'Lebanon', '+961'),
('LC', 'Saint Lucia', '+1-758'),
('LI', 'Liechtenstein', '+423'),
('LK', 'Sri Lanka', '+94'),
('LR', 'Liberia', '+231'),
('LS', 'Lesotho', '+266'),
('LT', 'Lithuania', '+370'),
('LU', 'Luxembourg', '+352'),
('LV', 'Latvia', '+371'),
('LY', 'Libya', '+218'),
('MA', 'Morocco', '+212'),
('MC', 'Monaco', '+377'),
('MD', 'Moldova, Republic of', '+373'),
('ME', 'Montenegro', '+382'),
('MF', 'Saint Martin (French part)', '+590'),
('MG', 'Madagascar', '+261'),
('MH', 'Marshall Islands', '+692'),
('MK', 'North Macedonia', '+389'),
('ML', 'Mali', '+223'),
('MM', 'Myanmar', '+95'),
('MN', 'Mongolia', '+976'),
('MO', 'Macao', '+853'),
('MP', 'Northern Mariana Islands', '+1-670'),
('MQ', 'Martinique', '+596'),
('MR', 'Mauritania', '+222'),
('MS', 'Montserrat', '+1-664'),
('MT', 'Malta', '+356'),
('MU', 'Mauritius', '+230'),
('MV', 'Maldives', '+960'),
('MW', 'Malawi', '+265'),
('MX', 'Mexico', '+52'),
('MY', 'Malaysia', '+60'),
('MZ', 'Mozambique', '+258'),
('NA', 'Namibia', '+264'),
('NC', 'New Caledonia', '+687'),
('NE', 'Niger', '+227'),
('NF', 'Norfolk Island', '+672'),
('NG', 'Nigeria', '+234'),
('NI', 'Nicaragua', '+505'),
('NL', 'Netherlands, Kingdom of the', '+31'),
('NO', 'Norway', '+47'),
('NP', 'Nepal', '+977'),
('NR', 'Nauru', '+674'),
('NU', 'Niue', '+683'),
('NZ', 'New Zealand', '+64'),
('OM', 'Oman', '+968'),
('PA', 'Panama', '+507'),
('PE', 'Peru', '+51'),
('PF', 'French Polynesia', '+689'),
('PG', 'Papua New Guinea', '+675'),
('PH', 'Philippines', '+63'),
('PK', 'Pakistan', '+92'),
('PL', 'Poland', '+48'),
('PM', 'Saint Pierre and Miquelon', '+508'),
('PN', 'Pitcairn', '+64'),
('PR', 'Puerto Rico', '+1-787'),
('PS', 'Palestine, State of', '+970'),
('PT', 'Portugal', '+351'),
('PW', 'Palau', '+680'),
('PY', 'Paraguay', '+595'),
('QA', 'Qatar', '+974'),
('RE', 'Réunion', '+262'),
('RO', 'Romania', '+40'),
('RS', 'Serbia', '+381'),
('RU', 'Russian Federation', '+7'),
('RW', 'Rwanda', '+250'),
('SA', 'Saudi Arabia', '+966'),
('SB', 'Solomon Islands', '+677'),
('SC', 'Seychelles', '+248'),
('SD', 'Sudan', '+249'),
('SE', 'Sweden', '+46'),
('SG', 'Singapore', '+65'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', '+290'),
('SI', 'Slovenia', '+386'),
('SJ', 'Svalbard and Jan Mayen', '+47'),
('SK', 'Slovakia', '+421'),
('SL', 'Sierra Leone', '+232'),
('SM', 'San Marino', '+378'),
('SN', 'Senegal', '+221'),
('SO', 'Somalia', '+252'),
('SR', 'Suriname', '+597'),
('SS', 'South Sudan', '+211'),
('ST', 'Sao Tome and Principe', '+239'),
('SV', 'El Salvador', '+503'),
('SX', 'Sint Maarten (Dutch part)', '+1-721'),
('SY', 'Syrian Arab Republic', '+963'),
('SZ', 'Eswatini', '+268'),
('TC', 'Turks and Caicos Islands', '+1-649'),
('TD', 'Chad', '+235'),
('TF', 'French Southern Territories', NULL),
('TG', 'Togo', '+228'),
('TH', 'Thailand', '+66'),
('TJ', 'Tajikistan', '+992'),
('TK', 'Tokelau', '+690'),
('TL', 'Timor-Leste', '+670'),
('TM', 'Turkmenistan', '+993'),
('TN', 'Tunisia', '+216'),
('TO', 'Tonga', '+676'),
('TR', 'Türkiye', '+90'),
('TT', 'Trinidad and Tobago', '+1-868'),
('TV', 'Tuvalu', '+688'),
('TW', 'Taiwan, Province of China', '+886'),
('TZ', 'Tanzania, United Republic of', '+255'),
('UA', 'Ukraine', '+380'),
('UG', 'Uganda', '+256'),
('UM', 'United States Minor Outlying Islands', NULL),
('US', 'United States of America', '+1'),
('UY', 'Uruguay', '+598'),
('UZ', 'Uzbekistan', '+998'),
('VA', 'Holy See', '+379'),
('VC', 'Saint Vincent and the Grenadines', '+1-784'),
('VE', 'Venezuela, Bolivarian Republic of', '+58'),
('VG', 'Virgin Islands (British)', '+1-284'),
('VI', 'Virgin Islands (U.S.)', '+1-340'),
('VN', 'Viet Nam', '+84'),
('VU', 'Vanuatu', '+678'),
('WF', 'Wallis and Futuna', '+681'),
('WS', 'Samoa', '+685'),
('XK', 'Kosovo', '+383'),
('YE', 'Yemen', '+967'),
('YT', 'Mayotte', '+262'),
('ZA', 'South Africa', '+27'),
('ZM', 'Zambia', '+260'),
('ZW', 'Zimbabwe', '+263');